name: RunScript

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      LINKEDIN_JSESSION_ID: ${{ secrets.LiJSess }} 
      LINKEDIN_LI_AT: ${{ secrets.LiLiat }} 
      DISCORD_WEBHOOK_URL: ${{ secrets.DiscordWbhkUrl }}
      TEST_ENV_VAR: $${{ secrets.Testy }}
    steps:
      - uses: actions/checkout@v4
      - name: "Set up python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: "Install pipenv"
        run: |
          pip install pipenv
      - name: "Print test secret var":
        run: echo ${{ env.TEST_ENV_VAR }}
      - name: "Run notification job"
        run: |
          pipenv install
          pipenv run python run.py